config/routes.rb
Rails.application.routes.draw do
  resources :brains
  resources :tweets
  resources :zombies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brain.rb
class Brain < ApplicationRecord
belongs_to :zombie

end

app/models/tweet.rb
class Tweet < ApplicationRecord
belongs_to :zombie

end

app/models/zombie.rb
class Zombie < ApplicationRecord
    validates_presence_of :nome
    
    validates_presence_of :bio
    validates_size_of :bio, minimum:4
    
    validates_presence_of :idade
    validates_numericality_of :idade
    
    validates_numericality_of :salario
    
    scope :roting, -> {
        where(apodrecendo: true)
    }
    
    scope :fresh, -> {
        where("idade<20")
    }
    
    scope :rot, -> {
        where("idade>20")
    }
    
    scope :recent, -> {
        order("created_at desc").limit(3)
    }
    
    has_many :tweets, dependent: :destroy
    
    has_one :brain, dependent: :destroy



before_save :make_apodrecendo
def make_apodrecendo
	self.apodrecendo=true if idade>20
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brains_controller.rb
class BrainsController < ApplicationController
  before_action :set_brain, only: [:show, :edit, :update, :destroy]

  # GET /brains
  # GET /brains.json
  def index
    @brains = Brain.all
  end

  # GET /brains/1
  # GET /brains/1.json
  def show
  end

  # GET /brains/new
  def new
    @brain = Brain.new
  end

  # GET /brains/1/edit
  def edit
  end

  # POST /brains
  # POST /brains.json
  def create
    @brain = Brain.new(brain_params)

    respond_to do |format|
      if @brain.save
        format.html { redirect_to @brain, notice: 'Brain was successfully created.' }
        format.json { render :show, status: :created, location: @brain }
      else
        format.html { render :new }
        format.json { render json: @brain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brains/1
  # PATCH/PUT /brains/1.json
  def update
    respond_to do |format|
      if @brain.update(brain_params)
        format.html { redirect_to @brain, notice: 'Brain was successfully updated.' }
        format.json { render :show, status: :ok, location: @brain }
      else
        format.html { render :edit }
        format.json { render json: @brain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brains/1
  # DELETE /brains/1.json
  def destroy
    @brain.destroy
    respond_to do |format|
      format.html { redirect_to brains_url, notice: 'Brain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brain
      @brain = Brain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brain_params
      params.require(:brain).permit(:zombie_id, :sabor)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:zombie_id, :status)
    end
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  before_action :set_zombie, only: [:show, :edit, :update, :destroy]

  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
  end

  # GET /zombies/new
  def new
    @zombie = Zombie.new
  end

  # GET /zombies/1/edit
  def edit
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(zombie_params)

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render :show, status: :created, location: @zombie }
      else
        format.html { render :new }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zombies/1
  # PATCH/PUT /zombies/1.json
  def update
    respond_to do |format|
      if @zombie.update(zombie_params)
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { render :show, status: :ok, location: @zombie }
      else
        format.html { render :edit }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie.destroy
    respond_to do |format|
      format.html { redirect_to zombies_url, notice: 'Zombie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zombie
      @zombie = Zombie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zombie_params
      params.require(:zombie).permit(:nome, :bio, :apodrecendo, :salario, :idade, :nascimento, :zombification)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brains_helper.rb
module BrainsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/brains/_form.html.erb
<%= form_for(brain) do |f| %>
  <% if brain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brain.errors.count, "error") %> prohibited this brain from being saved:</h2>

      <ul>
      <% brain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :zombie_id %>
    <%= f.number_field :zombie_id %>
  </div>

  <div class="field">
    <%= f.label :sabor %>
    <%= f.text_field :sabor %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brains/edit.html.erb
<h1>Editing Brain</h1>

<%= render 'form', brain: @brain %>

<%= link_to 'Show', @brain %> |
<%= link_to 'Back', brains_path %>

app/views/brains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brains</h1>

<table>
  <thead>
    <tr>
      <th>Zombie</th>
      <th>Sabor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brains.each do |brain| %>
      <tr>
        <td><%= brain.zombie_id %></td>
        <td><%= brain.sabor %></td>
        <td><%= link_to 'Show', brain %></td>
        <td><%= link_to 'Edit', edit_brain_path(brain) %></td>
        <td><%= link_to 'Destroy', brain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brain', new_brain_path %>

app/views/brains/new.html.erb
<h1>New Brain</h1>

<%= render 'form', brain: @brain %>

<%= link_to 'Back', brains_path %>

app/views/brains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zombie:</strong>
  <%= @brain.zombie_id %>
</p>

<p>
  <strong>Sabor:</strong>
  <%= @brain.sabor %>
</p>

<%= link_to 'Edit', edit_brain_path(@brain) %> |
<%= link_to 'Back', brains_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(tweet) do |f| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :zombie_id %>
    <%= f.number_field :zombie_id %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_area :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Zombie</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.zombie_id %></td>
        <td><%= tweet.status %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    
  </tbody>
</table>
    <% if @tweets.size == 0 %>
      <em> Não hã Tweets </em>
    <% end %>
<br><br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zombie:</strong>
  <%= @tweet.zombie_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @tweet.status %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

<%= link_to @tweet.zombie.name, @tweet.zombie %>

app/views/zombies/_form.html.erb
<%= form_for(zombie) do |f| %>
  <% if zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% zombie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>

  <div class="field">
    <%= f.label :apodrecendo %>
    <%= f.check_box :apodrecendo %>
  </div>

  <div class="field">
    <%= f.label :salario %>
    <%= f.text_field :salario %>
  </div>

  <div class="field">
    <%= f.label :idade %>
    <%= f.number_field :idade %>
  </div>

  <div class="field">
    <%= f.label :nascimento %>
    <%= f.datetime_select :nascimento %>
  </div>

  <div class="field">
    <%= f.label :zombification %>
    <%= f.date_select :zombification %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zombies/edit.html.erb
<h1>Editing Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

app/views/zombies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zombies</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Bio</th>
      <th>Apodrecendo</th>
      <th>Salario</th>
      <th>Idade</th>
      <th>Nascimento</th>
      <th>Zombification</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zombies.each do |zombie| %>
      <tr>
        <td><%= zombie.nome %></td>
        <td><%= zombie.bio %></td>
        <td><%= zombie.apodrecendo %></td>
        <td><%= zombie.salario %></td>
        <td><%= zombie.idade %></td>
        <td><%= zombie.nascimento %></td>
        <td><%= zombie.zombification %></td>
        <td><%= link_to 'Show', zombie %></td>
        <td><%= link_to 'Edit', edit_zombie_path(zombie) %></td>
        <td><%= link_to 'Destroy', zombie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zombie', new_zombie_path %>

app/views/zombies/new.html.erb
<h1>New Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to 'Back', zombies_path %>

app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @zombie.nome %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @zombie.bio %>
</p>

<p>
  <strong>Apodrecendo:</strong>
  <%= @zombie.apodrecendo %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @zombie.salario %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @zombie.idade %>
</p>

<p>
  <strong>Nascimento:</strong>
  <%= @zombie.nascimento %>
</p>

<p>
  <strong>Zombification:</strong>
  <%= @zombie.zombification %>
</p>

<%= link_to 'Edit', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>